modLoader = "javafml"
loaderVersion = "[37,)"
license = "CC0-1.0"

[[mods]]
modId = "villagersplus"
version = "${version}"
displayName = "VillagersPlus"
authors = "Lion"
description = '''
New villagers, new trades and new beautiful and useful workstations.
'''
logoFile = "villagersplus_logo.png"

[[dependencies.villagersplus]]
modId = "forge"
mandatory = true
versionRange = "[41.0.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagersplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"